# Generated by Django 5.2.17 on 2026-10-06 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "number",
                    models.CharField(
                        editable=False, max_length=32, unique=True, verbose_name="номер"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("confirmed", "Подтверждён"),
                            ("packed", "Собран"),
                            ("shipped", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменён"),
                            ("refunded", "Возврат"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255, verbose_name="имя покупателя")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("phone", models.CharField(max_length=32, verbose_name="телефон")),
                (
                    "shipping_method_title",
                    models.CharField(blank=True, max_length=255, verbose_name="доставка (снимок)"),
                ),
                ("shipping_address", models.TextField(blank=True, verbose_name="адрес доставки")),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="стоимость доставки",
                    ),
                ),
                (
                    "payment_method_title",
                    models.CharField(blank=True, max_length=255, verbose_name="оплата (снимок)"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="сумма товаров",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="скидка",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="итого",
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="валюта")),
                ("comment", models.TextField(blank=True, verbose_name="комментарий покупателя")),
                (
                    "manager_note",
                    models.TextField(
                        blank=True,
                        help_text="Покупателю не видна.",
                        verbose_name="заметка менеджера",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="название")),
                ("product_sku", models.CharField(max_length=64, verbose_name="артикул")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="цена за единицу"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="количество")),
                (
                    "total",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="сумма"),
                ),
            ],
            options={
                "verbose_name": "позиция заказа",
                "verbose_name_plural": "позиции заказа",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=20, verbose_name="из статуса"),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="в статус")),
                (
                    "comment",
                    models.CharField(blank=True, max_length=500, verbose_name="комментарий"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="когда")),
            ],
            options={
                "verbose_name": "изменение статуса",
                "verbose_name_plural": "история статусов",
                "ordering": ["-created_at"],
            },
        ),
    ]
