# Generated by Django 5.2.17 on 2026-10-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="код")),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="краткое описание"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Показывается покупателю на странице «спасибо» и в письме.",
                        verbose_name="инструкция после заказа",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("manual", "Без онлайн-оплаты (при получении / по счёту)")],
                        default="manual",
                        max_length=32,
                        verbose_name="провайдер",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ключи API и прочее. У каждого провайдера свои поля.",
                        verbose_name="настройки провайдера",
                    ),
                ),
            ],
            options={
                "verbose_name": "способ оплаты",
                "verbose_name_plural": "способы оплаты",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="сумма"),
                ),
                ("currency", models.CharField(default="RUB", max_length=3, verbose_name="валюта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="идентификатор у провайдера",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Сырые данные. Нужны при разборе спорных платежей.",
                        verbose_name="ответ провайдера",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="оплачен")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.paymentmethod",
                        verbose_name="способ оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "платёж",
                "verbose_name_plural": "платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
