# Generated by Django 5.2.17 on 2026-10-06 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="код")),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="описание"),
                ),
                (
                    "calculation",
                    models.CharField(
                        choices=[
                            ("fixed", "Фиксированная стоимость"),
                            ("free_from", "Бесплатно от суммы заказа"),
                            ("by_weight", "По весу заказа"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="схема расчёта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Для схемы «по весу» — стоимость базовой доставки.",
                        max_digits=12,
                        verbose_name="стоимость",
                    ),
                ),
                (
                    "free_from_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Только для схемы «бесплатно от суммы».",
                        max_digits=12,
                        null=True,
                        verbose_name="бесплатно от суммы",
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Только для схемы «по весу».",
                        max_digits=12,
                        null=True,
                        verbose_name="доплата за кг",
                    ),
                ),
                (
                    "requires_address",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите для самовывоза.",
                        verbose_name="нужен адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "способ доставки",
                "verbose_name_plural": "способы доставки",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
