# Generated by Django 5.2.17 on 2026-10-06 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="название")),
                ("slug", models.SlugField(max_length=128, unique=True, verbose_name="код")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Например: кг, см, Вт. Можно оставить пустым.",
                        max_length=32,
                        verbose_name="единица измерения",
                    ),
                ),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=False,
                        help_text="Значения этой характеристики попадут в фильтр каталога.",
                        verbose_name="использовать в фильтрах",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика",
                "verbose_name_plural": "характеристики",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — берётся название.",
                        max_length=255,
                        verbose_name="SEO: заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Рекомендуемая длина — до 160 символов.",
                        max_length=500,
                        verbose_name="SEO: описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO: ключевые слова"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="адрес (slug)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="изображение"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — берётся название.",
                        max_length=255,
                        verbose_name="SEO: заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Рекомендуемая длина — до 160 символов.",
                        max_length=500,
                        verbose_name="SEO: описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO: ключевые слова"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="название")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="адрес (slug)"),
                ),
                ("sku", models.CharField(max_length=64, unique=True, verbose_name="артикул")),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Показывается в списке товаров.",
                        max_length=300,
                        verbose_name="краткое описание",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="цена",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Зачёркнутая цена. Должна быть больше текущей.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="старая цена",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="остаток")),
                (
                    "track_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Выключено — товар всегда доступен к заказу.",
                        verbose_name="вести учёт остатка",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Нужен для расчёта доставки по весу.",
                        max_digits=8,
                        null=True,
                        verbose_name="вес, кг",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(db_index=True, default=False, verbose_name="рекомендуемый"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="значение")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="catalog.attribute",
                        verbose_name="характеристика",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "значение характеристики",
                "verbose_name_plural": "характеристики товара",
                "ordering": ["attribute__sort_order", "attribute__name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/%Y/%m/", verbose_name="изображение"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — подставится название товара.",
                        max_length=255,
                        verbose_name="альт. текст",
                    ),
                ),
                ("is_main", models.BooleanField(default=False, verbose_name="главное")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение товара",
                "verbose_name_plural": "изображения товара",
                "ordering": ["-is_main", "sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "sort_order"], name="catalog_cat_parent__57266d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category"], name="catalog_pro_is_acti_1a8de5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"], name="catalog_pro_is_feat_b968c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="catalog_product_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("old_price__isnull", True),
                    ("old_price__gt", models.F("price")),
                    _connector="OR",
                ),
                name="catalog_product_old_price_gt_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"), name="catalog_unique_product_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="catalog_one_main_image_per_product",
            ),
        ),
    ]
