# Generated by Django 5.2.17 on 2026-10-06 11:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_extensions"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="catalog_product_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
