# Generated by Django 5.2.17 on 2026-10-06 12:07

import apps.cms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_trgm_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="название")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.cms.models.upload_to_library, verbose_name="файл"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200, verbose_name="описание")),
            ],
            options={
                "verbose_name": "файл медиатеки",
                "verbose_name_plural": "медиатека",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="создано"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Пусто — берётся название.",
                        max_length=255,
                        verbose_name="SEO: заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Рекомендуемая длина — до 160 символов.",
                        max_length=500,
                        verbose_name="SEO: описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SEO: ключевые слова"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="адрес")),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("default", "Обычная"),
                            ("wide", "Во всю ширину"),
                            ("narrow", "Узкая колонка (текст)"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="вид страницы",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Короткий абзац под заголовком. Необязательно.",
                        verbose_name="вступление",
                    ),
                ),
                (
                    "show_title",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите, если заголовок уже есть в первом блоке.",
                        verbose_name="показывать заголовок",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Такие страницы нельзя удалить: на них ссылается код.",
                        verbose_name="системная",
                    ),
                ),
            ],
            options={
                "verbose_name": "страница",
                "verbose_name_plural": "страницы",
                "ordering": ("sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="NewSite3", max_length=120, verbose_name="название сайта"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Выводится рядом с логотипом и в подвале.",
                        max_length=200,
                        verbose_name="короткое описание",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to=apps.cms.models.upload_to_site, verbose_name="логотип"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.cms.models.upload_to_site,
                        verbose_name="иконка сайта",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="адрес")),
                (
                    "work_hours",
                    models.CharField(blank=True, max_length=120, verbose_name="часы работы"),
                ),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="WhatsApp")),
                ("youtube_url", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Короткий абзац о компании. Переносы строк сохраняются.",
                        verbose_name="текст в подвале",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Подставляется на страницах, где своё описание не задано.",
                        max_length=500,
                        verbose_name="описание сайта для поисковиков",
                    ),
                ),
                ("show_search", models.BooleanField(default=True, verbose_name="показывать поиск")),
                (
                    "show_phone_in_header",
                    models.BooleanField(default=True, verbose_name="телефон в шапке"),
                ),
                (
                    "head_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Счётчики и метрики. Вставляется как есть — только для администратора.",
                        verbose_name="код в <head>",
                    ),
                ),
                (
                    "body_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Чаты и виджеты. Вставляется как есть — только для администратора.",
                        verbose_name="код перед </body>",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
            ],
            options={
                "verbose_name": "настройки сайта",
                "verbose_name_plural": "настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("image", "Изображение"),
                            ("gallery", "Галерея"),
                            ("cta", "Призыв с кнопкой"),
                            ("products", "Подборка товаров"),
                            ("html", "Произвольный HTML"),
                            ("divider", "Разделитель"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="тип блока",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="заголовок блока"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Для типа «Текст» переносы строк превращаются в абзацы автоматически.",
                        verbose_name="текст",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.cms.models.upload_to_pages,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Текст для незрячих и на случай, если картинка не загрузится.",
                        max_length=200,
                        verbose_name="описание изображения",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="Можно относительную: /catalog/kremy/",
                        max_length=500,
                        verbose_name="ссылка",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(blank=True, max_length=100, verbose_name="текст кнопки"),
                ),
                (
                    "limit",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Для подборки товаров.", verbose_name="сколько товаров"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для подборки товаров. Пусто — избранные товары.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cms.page",
                        verbose_name="страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "блок",
                "verbose_name_plural": "блоки",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="BlockImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.cms.models.upload_to_pages, verbose_name="изображение"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200, verbose_name="описание")),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="подпись")),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cms.contentblock",
                        verbose_name="блок",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение галереи",
                "verbose_name_plural": "изображения галереи",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="активно"),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_index=True,
                        default=100,
                        help_text="Меньше значение — выше в списке.",
                        verbose_name="порядок",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("header", "Шапка сайта"), ("footer", "Подвал сайта")],
                        db_index=True,
                        default="header",
                        max_length=20,
                        verbose_name="где показывать",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="надпись")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Например /cart/ или https://example.com",
                        max_length=500,
                        verbose_name="произвольный адрес",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(default=False, verbose_name="открывать в новой вкладке"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="catalog.category",
                        verbose_name="категория каталога",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="cms.page",
                        verbose_name="страница сайта",
                    ),
                ),
            ],
            options={
                "verbose_name": "пункт меню",
                "verbose_name_plural": "меню сайта",
                "ordering": ("location", "sort_order", "pk"),
            },
        ),
    ]
